name: Build and push CentOS7 images to Quay.io registry
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and push s2i containers
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: "Dockerfile"
            registry_namespace: "centos7"
            registry_suffix: "-centos7"
          - dockerfile: "Dockerfile.c9s"
            registry_namespace: "sclorg"
            registry_suffix: ""

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
  
      - name: Get base image name
        id: base-image-name
        run: |
          # This command returns row with BASE_IMAGE_NAME
          row=$(grep "BASE_IMAGE_NAME" Makefile)
          # Return only base image name
          BASE_IMAGE_ROW=${row/BASE_IMAGE_NAME = /}
          echo ::set-output name=core_name::${{ matrix.registry_namespace }}/$BASE_IMAGE_ROW-core${{ matrix.suffix }}
          echo ::set-output name=base_name::${{ matrix.registry_namespace }}/$BASE_IMAGE_ROW-base${{ matrix.suffix }}

      - name: Set current date as env variable
        run: |
          echo "NOW=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build s2i-core image
        id: build-image-core
        # https://github.com/marketplace/actions/buildah-build
        uses: redhat-actions/buildah-build@v2
        with:
          dockerfiles: core/${{ matrix.dockerfile }}
          image: ${{ steps.base-image-name.outputs.core_name }}
          tags: latest c9s ${{ env.NOW }}-${{ github.sha }}

      - name: Push s2i-core CentOS 7 image to Quay.io
        id: push-to-quay-core
        if: ${{ matrix.registry_namespace == 'centos7' }}
        uses: redhat-actions/push-to-registry@v2.2
        with:
          image: ${{ steps.build-image-core.outputs.image }}
          tags: ${{ steps.build-image-core.outputs.tags }}
          registry: quay.io/${{ matrix.registry_namespace }}
          username: ${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}

      - name: Push s2i-core CentOS Stream 9 image to Quay.io
        id: push-to-quay-core
        if: ${{ matrix.registry_namespace != 'centos7' }}
        uses: redhat-actions/push-to-registry@v2.2
        with:
          image: ${{ steps.build-image-core.outputs.image }}
          tags: ${{ steps.build-image-core.outputs.tags }}
          registry: quay.io/${{ matrix.registry_namespace }}
          username: ${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_TOKEN  }}

      - name: Build s2i-base image
        id: build-image-base
        # https://github.com/marketplace/actions/buildah-build
        uses: redhat-actions/buildah-build@v2
        with:
          dockerfiles: core/${{ matrix.dockerfile }}
          image: ${{ steps.base-image-name.outputs.base_name }}
          tags: latest c9s ${{ env.NOW }}-${{ github.sha }}

      - name: Push s2i-core CentOS 7 image to Quay.io
        id: push-to-quay-base
        if: ${{ matrix.registry_namespace == 'centos7' }}
        uses: redhat-actions/push-to-registry@v2.2
        with:
          image: ${{ steps.build-image-base.outputs.image }}
          tags: ${{ steps.build-image-base.outputs.tags }}
          registry: quay.io/${{ matrix.registry_namespace }}
          username: ${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}

      - name: Push s2i-core CentOS Stream 9 image to Quay.io
        id: push-to-quay-base
        if: ${{ matrix.registry_namespace != 'centos7' }}
        uses: redhat-actions/push-to-registry@v2.2
        with:
          image: ${{ steps.build-image-base.outputs.image }}
          tags: ${{ steps.build-image-base.outputs.tags }}
          registry: quay.io/${{ matrix.registry_namespace }}
          username: ${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_TOKEN  }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay-core.outputs.registry-paths }} and ${{ steps.push-to-quay-base.outputs.registry-paths }}"
