name: Build and push CentOS7 images to Quay.io registry
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and push s2i containers
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: "Dockerfile"
            registry_namespace: "centos7"
            os_type: "centos7"
            registry_suffix: "-centos7"
          - dockerfile: "Dockerfile.c9s"
            registry_namespace: "sclorg"
            os_type: "c9s"
            registry_suffix: ""

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
  
      - name: Get base image name
        id: base-image-name
        run: |
          # This command returns row with BASE_IMAGE_NAME
          row=$(grep "BASE_IMAGE_NAME" Makefile)
          # Return only base image name
          BASE_IMAGE_ROW=${row/BASE_IMAGE_NAME = /}
          echo ::set-output name=core_name::${{ matrix.registry_namespace }}/$BASE_IMAGE_ROW-core${{ matrix.suffix }}
          echo ::set-output name=base_name::${{ matrix.registry_namespace }}/$BASE_IMAGE_ROW-base${{ matrix.suffix }}


      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io (centos7)
        if: ${{ matrix.os_type }} == 'centos7'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}

      - name: Login to Quay.io (c9s)
        if: ${{ matrix.os_type }} != 'centos7'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_TOKEN  }}

      - name: Set current date as env variable
        run: |
          echo "NOW=$(date +'%Y%m%d')" >> $GITHUB_ENV
          
      - name: Build and push s2i-core image
        if: success()
        id: build_push_core
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./core/${{ matrix.dockerfile }}
          tags: ${{ steps.base-image-name.outputs.core_name }}:latest,${{ steps.base-image-name.outputs.core_name }}:c9s,${{ steps.base-image-name.outputs.core_name }}:${{ env.NOW }}-${{ github.sha }}
          push: true

      - name: Build and push s2i-base image
        if: success()
        id: build_push_base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base/${{ matrix.dockerfile }}
          tags: ${{ steps.base-image-name.outputs.base_name }}:latest,${{ steps.base-image-name.outputs.base_name }}:c9s,${{ steps.base-image-name.outputs.base_name }}:${{ env.NOW }}-${{ github.sha }}
          push: true

      - name: Print image url
        run: echo "Image pushed to ${{ steps.build_push_core.outputs.digest }} and ${{ steps.build_push_base.outputs.digest }}"
